[tool.poetry]
name = "telegram_bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "*"
aiogram = "^3.0"
aiohttp = "*"
aiosignal = "*"
annotated-types = "*"
anyio = "*"
apscheduler = "*"
async-timeout = "*"
attrs = "*"
babel = "*"
backports.tarfile = "*"
certifi = "*"
chardet = "*"
charset-normalizer = "*"
click = "*"
click-log = "*"
colorama = "*"
dataclasses = "*"
deprecation = "*"
distro = "*"
docutils = "*"
dotty-dict = "*"
exceptiongroup = "*"
frozenlist = "*"
gitdb = "*"
gitpython = "*"
gotrue = "*"
h11 = "*"
hiredis = "*"
httpcore = "*"
httpx = "*"
idna = "*"
importlib_metadata = "*"
iniconfig = "*"
install = "*"
invoke = "*"
jaraco.classes = "*"
jaraco.context = "*"
jaraco.functools = "*"
keyring = "*"
magic-filter = "*"
more-itertools = "*"
multidict = "*"
mypy-extensions = "*"
nh3 = "*"
numpy = "*"
openai = "*"
packaging = "*"
pandas = "*"
pipdeptree = "*"
pkginfo = "*"
pluggy = "*"
postgrest = "*"
postgrest-py = "*"
py = "*"
pydantic = "*"
pydantic-core = "*"
pydub = "*"
pygame = "*"
pygments = "*"
pytest = "*"
python-dateutil = "*"
python-dotenv = "*"
python-gitlab = "*"
python-semantic-release = "*"
pytz = "*"
readme-renderer = "*"
realtime = "*"
realtime-py = "*"
requests = "*"
requests-toolbelt = "*"
rfc3986 = "*"
semver = "*"
six = "*"
smmap = "*"
sniffio = "*"
sqlalchemy = "*"
storage3 = "*"
strenum = "*"
supabase = "*"
supafunc = "*"
toml = "*"
tomli = "*"
tomlkit = "*"
tqdm = "*"
twine = "*"
typing-extensions = "*"
tzdata = "*"
tzlocal = "*"
urllib3 = "*"
websocket-client = "*"
websockets = "*"
yarl = "*"
zipp = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
